### ISSUE TITLE
where is "recources/download_resources.sh

### ISSUE THREAD

**Issue by guruace** [ali-design/GenRep#4]

**Comment by guruace** [comment]
I could not find directory 'resources" or file /download_resources.sh.

**Comment by ali-design** [comment]
resources meant generators like BigBiGAN, BigGAN, StyleGAN. You can find each on their own git, if you need them. You should be able to train and test using the current codes we provide here (assuming you have access to your data you generated by using any of those generators). 
Please look at the updated README for more instructions.
