### ISSUE TITLE
Why the image size is not 128?

### ISSUE THREAD

**Issue by xiao7199** [ali-design/GenRep#8]
Hi, the image size in main_unified is multiplied by 0.85. The paper says the training image size is 128 while the actual image size in this code is 128 * 0.85. Can you explain why?

**Comment by xavierpuigf** [comment]
Hi! We follow the same procedure as people typically do with SSL in ImageNet but at half the resolution: at the original resolution the common approach is to resize ImageNet to 256x256 and take crops of 224x224 (85% of 256). At half the resolution, we resize to 128x128 and take crops of 112x112. During training the crops are random and during testing we take the center crop.

**Comment by xiao7199** [comment]
Thanks for the prompt reply!  In Appendix A, the cropping details, there are lines "for methods without Tz we take a 128 × 128 pixel center square crop" and "crop to produce the 128 × 128 pixel inputs to our models". So are you using 128x128 for training and 112x112 for testing?  If so, why the image size is still multiplied by 0.85, given that the image size is 128 already? (https://github.com/ali-design/GenRep/blob/master/main_unified.py#L191)

**Comment by xavierpuigf** [comment]
I believe this is an error in the text, we produce 112x112 pixel inputs to our models.

**Comment by xiao7199** [comment]
Thanks!
